apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: onlyoffice
  name: onlyoffice-documentserver-claim
  labels:
    app: onlyoffice-documentserver
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
