apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: onlyoffice-rabbitmq
  name: onlyoffice-rabbitmq
  namespace: onlyoffice  
spec:
  ports:
  - name: "5672"
    port: 5672
    targetPort: 5672
  selector:
    io.kompose.service: onlyoffice-rabbitmq
status:
  loadBalancer: {}
