apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: onlyoffice-documentserver
  name: onlyoffice-documentserver
  namespace: onlyoffice  
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    io.kompose.service: onlyoffice-documentserver
status:
  loadBalancer: {}
